version: 2.1

defaults: &dockerImage
    docker:
        - image: circleci/node:13.8.0

jobs:
    build:
        <<: *dockerImage
        steps:
            # - checkout
            - command: echo "build ..."
    test:
        <<: *dockerImage
        steps:
            # - checkout
            - command: echo "test ..."
    analyze:
        <<: *dockerImage
        steps:
            # - checkout
            - command: echo "analyze"
workflows:
    appWorkFlow:
        jobs:
            - build
            - test:
                - requires:
                    - build
            - analyze:
                - requires: test