defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit

workflows:
  create_ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test